name: autodeploy

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Run lint (& test, cov ...)
        run: |
          npm install 
          npm run lint
          echo "test, cov..."
          echo "ok"

  deploy_to_sit:
    needs: ci

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Change config/env to sit
        run: |
          echo "sit" > config/env
          echo "confirm config/env:"
          cat config/env

      - name: Deploy to sit server
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.tencentcloud_DEPLOY_KEY}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: '.'
          dest: '${{ secrets.tencentcloud_USERNAME }}@${{ secrets.tencentcloud_HOST }}:./yumecoder/server_nodejs/sit/source'

      - name: Run docker commands
        uses: appleboy/ssh-action@master
        env:
          TC_USERNAME: ${{ secrets.tencentcloud_USERNAME }}
        with:
          host: ${{ secrets.tencentcloud_HOST }}
          username: ${{ secrets.tencentcloud_USERNAME }}
          key: ${{ secrets.tencentcloud_DEPLOY_KEY }}
          envs: TC_USERNAME
          script: |
            cd /home/$TC_USERNAME/yumecoder/server_nodejs/sit
            ./DockerBootstrap.sh

  deploy_to_prod:
    needs: deploy_to_sit

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Change config/env to prod
        run: |
          echo "prod" > config/env
          echo "confirm config/env:"
          cat config/env

      - name: Deploy to prod server
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.tencentcloud_DEPLOY_KEY}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: '.'
          dest: '${{ secrets.tencentcloud_USERNAME }}@${{ secrets.tencentcloud_HOST }}:./yumecoder/server_nodejs/prod/source'

      - name: Run docker commands
        uses: appleboy/ssh-action@master
        env:
          TC_USERNAME: ${{ secrets.tencentcloud_USERNAME }}
        with:
          host: ${{ secrets.tencentcloud_HOST }}
          username: ${{ secrets.tencentcloud_USERNAME }}
          key: ${{ secrets.tencentcloud_DEPLOY_KEY }}
          envs: TC_USERNAME
          script: |
            cd /home/$TC_USERNAME/yumecoder/server_nodejs/prod
            ./DockerBootstrap.sh
